name = "todo-app"
env = { "NODE_ENV" = "production" }
main = "app/workers"
compatibility_date = "2024-11-17"

[[d1_databases]]
binding = "DB"
database_name = "todos"
database_id = "aa80297c-058c-445b-b28b-3fe5b2c66155"
migrations_dir = "app/migrations"

# ローカル開発用の環境設定（miniflare用）
[env.local]
name = "local"

[[env.local.d1_databases]]
binding = "DB"
database_name = "todos"
database_id = "aa80297c-058c-445b-b28b-3fe5b2c66155"
