name = "todo-app"
main = "app/workers"
compatibility_date = "2024-11-17"

[[d1_databases]]
binding = "DB"
database_name = "todos"
database_id = "7ba4f6be-b622-4d33-b432-80143706839b"
migrations_dir = "app/migrations"

# ローカル開発用の環境設定（miniflare用）
[env.local]
name = "local"

[[env.local.d1_databases]]
binding = "DB"
database_name = "todos"
database_id = "7ba4f6be-b622-4d33-b432-80143706839b"
